import logging
from pyDatalog import pyDatalog, pyEngine
pyEngine.Logging = True
logging.basicConfig(level=logging.INFO)
pyDatalog.create_terms('missing_log,pre,post,missing_log_provBYWKQXE08LQHSR03,pre_prov2OWEF7AKHDC7JMI7,post_provS7V2AGFBAERDQQX6,log,node,bcast,crash')
pyDatalog.create_terms('A,Pl,Time,X,THISISAWILDCARD')
pyDatalog.assert_fact('node',"a","b",1)
pyDatalog.assert_fact('node',"a","c",1)
pyDatalog.assert_fact('node',"b","a",1)
pyDatalog.assert_fact('node',"b","c",1)
pyDatalog.assert_fact('node',"c","a",1)
pyDatalog.assert_fact('node',"c","b",1)
pyDatalog.assert_fact('bcast',"a","hello",1)
pyDatalog.assert_fact('clock','a','a','1','2')
pyDatalog.assert_fact('clock','a','b','1','2')
pyDatalog.assert_fact('clock','a','c','1','2')
pyDatalog.assert_fact('clock','a','d','1','2')
pyDatalog.assert_fact('clock','b','a','1','2')
pyDatalog.assert_fact('clock','b','b','1','2')
pyDatalog.assert_fact('clock','b','c','1','2')
pyDatalog.assert_fact('clock','b','d','1','2')
pyDatalog.assert_fact('clock','c','a','1','2')
pyDatalog.assert_fact('clock','c','b','1','2')
pyDatalog.assert_fact('clock','c','c','1','2')
pyDatalog.assert_fact('clock','c','d','1','2')
pyDatalog.assert_fact('clock','d','a','1','2')
pyDatalog.assert_fact('clock','d','b','1','2')
pyDatalog.assert_fact('clock','d','c','1','2')
pyDatalog.assert_fact('clock','d','d','1','2')
pyDatalog.assert_fact('clock','a','a','2','3')
pyDatalog.assert_fact('clock','a','b','2','3')
pyDatalog.assert_fact('clock','a','c','2','3')
pyDatalog.assert_fact('clock','a','d','2','3')
pyDatalog.assert_fact('clock','b','a','2','3')
pyDatalog.assert_fact('clock','b','b','2','3')
pyDatalog.assert_fact('clock','b','c','2','3')
pyDatalog.assert_fact('clock','b','d','2','3')
pyDatalog.assert_fact('clock','c','a','2','3')
pyDatalog.assert_fact('clock','c','b','2','3')
pyDatalog.assert_fact('clock','c','c','2','3')
pyDatalog.assert_fact('clock','c','d','2','3')
pyDatalog.assert_fact('clock','d','a','2','3')
pyDatalog.assert_fact('clock','d','b','2','3')
pyDatalog.assert_fact('clock','d','c','2','3')
pyDatalog.assert_fact('clock','d','d','2','3')
pyDatalog.assert_fact('clock','a','a','3','4')
pyDatalog.assert_fact('clock','a','b','3','4')
pyDatalog.assert_fact('clock','a','c','3','4')
pyDatalog.assert_fact('clock','a','d','3','4')
pyDatalog.assert_fact('clock','b','a','3','4')
pyDatalog.assert_fact('clock','b','b','3','4')
pyDatalog.assert_fact('clock','b','c','3','4')
pyDatalog.assert_fact('clock','b','d','3','4')
pyDatalog.assert_fact('clock','c','a','3','4')
pyDatalog.assert_fact('clock','c','b','3','4')
pyDatalog.assert_fact('clock','c','c','3','4')
pyDatalog.assert_fact('clock','c','d','3','4')
pyDatalog.assert_fact('clock','d','a','3','4')
pyDatalog.assert_fact('clock','d','b','3','4')
pyDatalog.assert_fact('clock','d','c','3','4')
pyDatalog.assert_fact('clock','d','d','3','4')
(missing_log(A,Pl,Time)) <= (log(X,Pl,Time)) & (node(X,A,Time)) & (~(log(A,Pl,Time)))
(pre(X,Pl,Time)) <= (log(X,Pl,Time)) & (~(bcast(X,Pl,1)) )& (~(crash(X,X,THISISAWILDCARD,Time)))
(post(X,Pl,Time)) <= (log(X,Pl,Time)) & (~(missing_log(THISISAWILDCARD,Pl,Time)))
(missing_log_provBYWKQXE08LQHSR03(X,Pl,Time,A)) <= (log(X,Pl,Time)) & (node(X,A,Time)) & (~(log(A,Pl,Time)))
(pre_prov2OWEF7AKHDC7JMI7(X,Pl,Time)) <= (log(X,Pl,Time)) & (~(bcast(X,Pl,1)) )& (~(crash(X,X,THISISAWILDCARD,Time)))
(post_provS7V2AGFBAERDQQX6(X,Pl,Time)) <= (log(X,Pl,Time)) & (~(missing_log(THISISAWILDCARD,Pl,Time)))
print ( pre(X,Pl,Time).data[0] )
print ( post(X,Pl,Time).data[0] )
